name: SauceDemo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      USER : ${{secrets.SD_USER}}
      PASSWORD : ${{secrets.SD_PASSWORD}}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn compile -q

    - name: Run tests with Allure
      run: mvn test -q

    - name: Generate Allure Report
      run: mvn allure:report -q

    - name: Archive Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: target/allure-results

    - name: Archive Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/allure-report

    - name: Publish Allure Report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        allure_results: target/allure-results
        gh_pages: gh-pages
        allure_report: target/allure-report
        keep_reports: 20
    - name: Run tests
      run: mvn clean test -Duser=$USER -Dpassword=$PASSWORD
      working-directory: ./SauceDemo