name: SauceDemo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      USER: ${{secrets.SD_USER}}
      PASSWORD: ${{secrets.SD_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents:"
          ls -la
          echo "Checking SauceDemo directory:"
          if [ -d "SauceDemo" ]; then
            echo "✅ SauceDemo directory exists"
            ls -la SauceDemo/
          else
            echo "❌ SauceDemo directory not found"
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build project
        run: cd SauceDemo && mvn compile -q

      - name: Run tests with Allure
        run: cd SauceDemo && mvn test -q -Duser=$USER -Dpassword=$PASSWORD

      - name: Generate Allure Report
        run: cd SauceDemo && mvn allure:report -q

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: SauceDemo/target/allure-results
          retention-days: 7

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: SauceDemo/target/allure-report
          retention-days: 7

      - name: Deploy Allure report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: SauceDemo/target/allure-report
          keep_files: true