name: SauceDemo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify project structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in root directory:"
          ls -la
          echo "Checking SauceDemo directory:"
          ls -la SauceDemo/
          echo "pom.xml found in SauceDemo/ directory ✅"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn compile -q
        working-directory: ./SauceDemo

      - name: Run tests
        run: mvn test -q -Duser=${{secrets.SD_USER}} -Dpassword=${{secrets.SD_PASSWORD}}
        working-directory: ./SauceDemo

      - name: Generate Allure Report
        run: mvn allure:report -q
        working-directory: ./SauceDemo

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: SauceDemo/target/allure-results
          retention-days: 7

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: SauceDemo/target/allure-report
          retention-days: 7

      - name: Publish Allure Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: SauceDemo/target/allure-report
          keep_files: true