name: SauceDemo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify project structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in root directory:"
          ls -la
          echo "Checking for pom.xml:"
          if [ -f "pom.xml" ]; then
            echo "✅ pom.xml found in root!"
            cat pom.xml | head -10
          else
            echo "❌ pom.xml not found in root!"
            echo "Searching for pom.xml in subdirectories:"
            find . -name "pom.xml" -type f
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn compile -q

      - name: Run tests
        run: mvn test -q -Duser=${{secrets.SD_USER}} -Dpassword=${{secrets.SD_PASSWORD}}

      - name: Generate Allure Report
        run: mvn allure:report -q

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          retention-days: 7

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
          retention-days: 7